version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    # Add any additional configuration for the backend service, if necessary

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Add any additional configuration for the frontend service, if necessary
